FROM node:22-alpine
COPY --from=oven/bun:1.4.2-alpine /usr/local/bin/bun /usr/local/bin/bun
ENV PATH="/root/.bun/bin:$PATH"

RUN apk add --no-cache libc6-compat

# Set working directory
WORKDIR /app

COPY . .

RUN bun add -g turbo@2.9.18
RUN bun install --frozen-lockfile

EXPOSE 3002

ENV VITE_SPACE_BASE_PATH="/spaces"

VOLUME [ "/app/node_modules", "/app/apps/space/node_modules"]

CMD ["turbo", "run", "dev", "--filter=space"]
