/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */

import React, { useState } from "react";
import { Sparkles, ChevronDown, FileText, FileSpreadsheet, Presentation, Check, Loader2 } from "lucide-react";
import { cn } from "@plane/utils";
import { AVAILABLE_CONTEXTS, TOP_TEMPLATES } from "./mock-data";
import { TypeIcon } from "./type-icon";
import type { TDetailLevel, TDocumentFormat, TDocumentTone, TDocumentType, IGeneratedDocument } from "./types";

interface IAIGeneratorFormProps {
  selectedTemplate: TDocumentType;
  onTemplateChange: (tpl: TDocumentType) => void;
  onDocumentGenerated: (doc: IGeneratedDocument) => void;
}

export const AIGeneratorForm: React.FC<IAIGeneratorFormProps> = ({
  selectedTemplate,
  onTemplateChange,
  onDocumentGenerated,
}) => {
  const [context, setContext] = useState<string>(AVAILABLE_CONTEXTS[0]);
  const [additionalContext, setAdditionalContext] = useState<string>("");
  const [format, setFormat] = useState<TDocumentFormat>("DOCX");
  const [tone, setTone] = useState<TDocumentTone>("Professional");
  const [detailLevel, setDetailLevel] = useState<TDetailLevel>("Comprehensive");

  const [isTemplateMenuOpen, setIsTemplateMenuOpen] = useState(false);
  const [isContextMenuOpen, setIsContextMenuOpen] = useState(false);
  const [isToneMenuOpen, setIsToneMenuOpen] = useState(false);
  const [isDetailMenuOpen, setIsDetailMenuOpen] = useState(false);

  const [isGenerating, setIsGenerating] = useState(false);

  const tones: TDocumentTone[] = ["Professional", "Formal", "Technical", "Executive", "Casual"];
  const detailLevels: TDetailLevel[] = ["Concise", "Standard", "Comprehensive", "In-depth"];

  const handleGenerate = () => {
    if (isGenerating) return;
    setIsGenerating(true);

    const newDoc: IGeneratedDocument = {
      id: `doc-${Date.now()}`,
      title: `${selectedTemplate} - ${context}`,
      description: additionalContext.trim()
        ? additionalContext.slice(0, 50) + (additionalContext.length > 50 ? "..." : "")
        : `AI Generated ${selectedTemplate.toLowerCase()} for ${context}`,
      type: selectedTemplate,
      context,
      createdBy: {
        name: "You (AI Assisted)",
        initials: "ME",
      },
      createdAt: "Just now",
      status: "Completed",
      format,
      content: `# ${selectedTemplate} - ${context}\n\n**Generated:** Just now\n**Tone:** ${tone} | **Detail Level:** ${detailLevel}\n**Format:** ${format}\n\n## Overview\nThis document was generated by AI using project context and workspace knowledge base.\n\n### Specifications & Details\n- **Project Scope:** ${context}\n${additionalContext ? `- **Additional Directives:** ${additionalContext}\n` : ""}- **Output Profile:** ${tone} tone with ${detailLevel.toLowerCase()} detail level.`,
    };

    setTimeout(() => {
      setIsGenerating(false);
      onDocumentGenerated(newDoc);
    }, 1200);
  };

  return (
    <div className="shadow-xs flex flex-col rounded-xl border border-subtle bg-surface-1 p-5">
      {/* Title */}
      <div className="mb-5">
        <h2 className="text-base font-semibold text-primary">AI Document Generator</h2>
        <p className="text-xs mt-0.5 text-secondary">Generate documents with AI in minutes</p>
      </div>

      <div className="space-y-4">
        {/* STEP 1: Select Template */}
        <div>
          <div className="mb-1.5 flex items-center gap-2">
            <span className="bg-blue-600 flex size-4 items-center justify-center rounded-full text-[10px] font-bold text-white">
              1
            </span>
            <label className="text-xs font-semibold text-primary">Select Template</label>
          </div>
          <div className="relative">
            <button
              type="button"
              onClick={() => {
                setIsTemplateMenuOpen(!isTemplateMenuOpen);
                setIsContextMenuOpen(false);
                setIsToneMenuOpen(false);
                setIsDetailMenuOpen(false);
              }}
              className="text-xs flex w-full items-center justify-between rounded-lg border border-subtle bg-surface-2 px-3 py-2 font-medium text-primary transition-colors hover:border-strong"
            >
              <div className="flex items-center gap-2">
                <TypeIcon type={selectedTemplate} size={15} />
                <span>{selectedTemplate}</span>
              </div>
              <ChevronDown size={14} className="text-placeholder" />
            </button>

            {isTemplateMenuOpen && (
              <div className="shadow-lg absolute z-30 mt-1 w-full rounded-lg border border-subtle bg-surface-1 py-1">
                {TOP_TEMPLATES.map((tpl) => (
                  <button
                    key={tpl.id}
                    type="button"
                    onClick={() => {
                      onTemplateChange(tpl.name);
                      if (tpl.defaultFormat) setFormat(tpl.defaultFormat);
                      setIsTemplateMenuOpen(false);
                    }}
                    className={cn(
                      "text-xs flex w-full items-center justify-between px-3 py-2 text-left transition-colors hover:bg-surface-2",
                      selectedTemplate === tpl.name &&
                        "bg-blue-50/60 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400 font-medium"
                    )}
                  >
                    <div className="flex items-center gap-2">
                      <TypeIcon type={tpl.name} size={14} />
                      <span>{tpl.title}</span>
                    </div>
                    {selectedTemplate === tpl.name && <Check size={13} className="text-blue-600 dark:text-blue-400" />}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* STEP 2: Select Context */}
        <div>
          <div className="mb-1.5 flex items-center gap-2">
            <span className="bg-blue-600 flex size-4 items-center justify-center rounded-full text-[10px] font-bold text-white">
              2
            </span>
            <label className="text-xs font-semibold text-primary">Select Context</label>
          </div>
          <div className="relative">
            <button
              type="button"
              onClick={() => {
                setIsContextMenuOpen(!isContextMenuOpen);
                setIsTemplateMenuOpen(false);
                setIsToneMenuOpen(false);
                setIsDetailMenuOpen(false);
              }}
              className="text-xs flex w-full items-center justify-between rounded-lg border border-subtle bg-surface-2 px-3 py-2 font-medium text-primary transition-colors hover:border-strong"
            >
              <div className="flex items-center gap-2 truncate">
                <span className="truncate">{context}</span>
                <span className="font-normal rounded bg-layer-2 px-1.5 py-0.5 text-[10px] text-secondary">Project</span>
              </div>
              <ChevronDown size={14} className="ml-2 shrink-0 text-placeholder" />
            </button>

            {isContextMenuOpen && (
              <div className="shadow-lg absolute z-30 mt-1 max-h-48 w-full overflow-y-auto rounded-lg border border-subtle bg-surface-1 py-1">
                {AVAILABLE_CONTEXTS.map((item) => (
                  <button
                    key={item}
                    type="button"
                    onClick={() => {
                      setContext(item);
                      setIsContextMenuOpen(false);
                    }}
                    className={cn(
                      "text-xs flex w-full items-center justify-between px-3 py-2 text-left transition-colors hover:bg-surface-2",
                      context === item &&
                        "bg-blue-50/60 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400 font-medium"
                    )}
                  >
                    <span className="truncate">{item}</span>
                    {context === item && <Check size={13} className="text-blue-600 dark:text-blue-400 ml-2 shrink-0" />}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* STEP 3: Additional Context (Optional) */}
        <div>
          <div className="mb-1.5 flex items-center gap-2">
            <span className="bg-blue-600 flex size-4 items-center justify-center rounded-full text-[10px] font-bold text-white">
              3
            </span>
            <label className="text-xs font-semibold text-primary">Additional Context (Optional)</label>
          </div>
          <div className="relative">
            <textarea
              rows={3}
              maxLength={1000}
              value={additionalContext}
              onChange={(e) => setAdditionalContext(e.target.value)}
              placeholder="Add more details about the project, scope, or enter specific requirements..."
              className="text-xs focus:border-blue-500 w-full resize-none rounded-lg border border-subtle bg-surface-2 p-2.5 text-primary transition-colors placeholder:text-placeholder focus:outline-none"
            />
            <div className="absolute right-2 bottom-2 text-[10px] text-placeholder">
              {additionalContext.length}/1000
            </div>
          </div>
        </div>

        {/* STEP 4: Output Preferences */}
        <div>
          <div className="mb-2 flex items-center gap-2">
            <span className="bg-blue-600 flex size-4 items-center justify-center rounded-full text-[10px] font-bold text-white">
              4
            </span>
            <label className="text-xs font-semibold text-primary">Output Preferences</label>
          </div>

          <div className="space-y-3 pl-6">
            {/* Format buttons */}
            <div>
              <span className="mb-1.5 block text-[11px] font-medium text-secondary">Document Format</span>
              <div className="grid grid-cols-3 gap-2">
                {/* DOCX */}
                <button
                  type="button"
                  onClick={() => setFormat("DOCX")}
                  className={cn(
                    "text-xs flex items-center justify-center gap-1.5 rounded-lg border py-2 font-medium transition-all",
                    format === "DOCX"
                      ? "border-blue-500 bg-blue-50/70 text-blue-600 shadow-xs dark:bg-blue-950/50 dark:text-blue-400 dark:border-blue-500"
                      : "border-subtle bg-surface-2 text-secondary hover:border-strong hover:text-primary"
                  )}
                >
                  <FileText
                    size={14}
                    className={format === "DOCX" ? "text-blue-600 dark:text-blue-400" : "text-blue-500"}
                  />
                  <span>DOCX</span>
                </button>

                {/* PDF */}
                <button
                  type="button"
                  onClick={() => setFormat("PDF")}
                  className={cn(
                    "text-xs flex items-center justify-center gap-1.5 rounded-lg border py-2 font-medium transition-all",
                    format === "PDF"
                      ? "border-blue-500 bg-blue-50/70 text-blue-600 shadow-xs dark:bg-blue-950/50 dark:text-blue-400 dark:border-blue-500"
                      : "border-subtle bg-surface-2 text-secondary hover:border-strong hover:text-primary"
                  )}
                >
                  <FileSpreadsheet
                    size={14}
                    className={format === "PDF" ? "text-red-600 dark:text-red-400" : "text-red-500"}
                  />
                  <span>PDF</span>
                </button>

                {/* PPTX */}
                <button
                  type="button"
                  onClick={() => setFormat("PPTX")}
                  className={cn(
                    "text-xs flex items-center justify-center gap-1.5 rounded-lg border py-2 font-medium transition-all",
                    format === "PPTX"
                      ? "border-blue-500 bg-blue-50/70 text-blue-600 shadow-xs dark:bg-blue-950/50 dark:text-blue-400 dark:border-blue-500"
                      : "border-subtle bg-surface-2 text-secondary hover:border-strong hover:text-primary"
                  )}
                >
                  <Presentation
                    size={14}
                    className={format === "PPTX" ? "text-orange-600 dark:text-orange-400" : "text-orange-500"}
                  />
                  <span>PPTX</span>
                </button>
              </div>
            </div>

            {/* Tone Selector */}
            <div>
              <span className="mb-1 block text-[11px] font-medium text-secondary">Tone</span>
              <div className="relative">
                <button
                  type="button"
                  onClick={() => {
                    setIsToneMenuOpen(!isToneMenuOpen);
                    setIsDetailMenuOpen(false);
                    setIsTemplateMenuOpen(false);
                    setIsContextMenuOpen(false);
                  }}
                  className="text-xs flex w-full items-center justify-between rounded-lg border border-subtle bg-surface-2 px-3 py-1.5 text-primary transition-colors hover:border-strong"
                >
                  <span>{tone}</span>
                  <ChevronDown size={13} className="text-placeholder" />
                </button>
                {isToneMenuOpen && (
                  <div className="shadow-lg absolute z-30 mt-1 w-full rounded-lg border border-subtle bg-surface-1 py-1">
                    {tones.map((t) => (
                      <button
                        key={t}
                        type="button"
                        onClick={() => {
                          setTone(t);
                          setIsToneMenuOpen(false);
                        }}
                        className={cn(
                          "text-xs flex w-full items-center justify-between px-3 py-1.5 text-left transition-colors hover:bg-surface-2",
                          tone === t && "bg-blue-50/60 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400 font-medium"
                        )}
                      >
                        <span>{t}</span>
                        {tone === t && <Check size={12} className="text-blue-600 dark:text-blue-400" />}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Detail Level */}
            <div>
              <span className="mb-1 block text-[11px] font-medium text-secondary">Detail Level</span>
              <div className="relative">
                <button
                  type="button"
                  onClick={() => {
                    setIsDetailMenuOpen(!isDetailMenuOpen);
                    setIsToneMenuOpen(false);
                    setIsTemplateMenuOpen(false);
                    setIsContextMenuOpen(false);
                  }}
                  className="text-xs flex w-full items-center justify-between rounded-lg border border-subtle bg-surface-2 px-3 py-1.5 text-primary transition-colors hover:border-strong"
                >
                  <span>{detailLevel}</span>
                  <ChevronDown size={13} className="text-placeholder" />
                </button>
                {isDetailMenuOpen && (
                  <div className="shadow-lg absolute z-30 mt-1 w-full rounded-lg border border-subtle bg-surface-1 py-1">
                    {detailLevels.map((lvl) => (
                      <button
                        key={lvl}
                        type="button"
                        onClick={() => {
                          setDetailLevel(lvl);
                          setIsDetailMenuOpen(false);
                        }}
                        className={cn(
                          "text-xs flex w-full items-center justify-between px-3 py-1.5 text-left transition-colors hover:bg-surface-2",
                          detailLevel === lvl &&
                            "bg-blue-50/60 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400 font-medium"
                        )}
                      >
                        <span>{lvl}</span>
                        {detailLevel === lvl && <Check size={12} className="text-blue-600 dark:text-blue-400" />}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Generate Button */}
        <div className="pt-2">
          <button
            type="button"
            disabled={isGenerating}
            onClick={handleGenerate}
            className="bg-blue-600 text-xs shadow-sm hover:bg-blue-700 flex w-full items-center justify-center gap-2 rounded-lg py-2.5 font-semibold text-white transition-all active:scale-[0.99] disabled:opacity-75"
          >
            {isGenerating ? (
              <>
                <Loader2 size={15} className="animate-spin" />
                <span>Generating Document...</span>
              </>
            ) : (
              <>
                <Sparkles size={15} />
                <span>Generate Document</span>
              </>
            )}
          </button>
          <p className="mt-2 text-center text-[11px] text-placeholder">
            AI will use project context and knowledge base
          </p>
        </div>
      </div>
    </div>
  );
};
