/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */

import type { IOpportunityItem, IPipelineStageCount } from "./types";

export const PIPELINE_STAGES: IPipelineStageCount[] = [
  { stage: "All", count: 18, color: "blue" },
  { stage: "Lead", count: 6, color: "blue" },
  { stage: "Qualified", count: 5, color: "green" },
  { stage: "POC / Discovery", count: 4, color: "purple" },
  { stage: "Proposal", count: 2, color: "orange" },
  { stage: "Negotiation", count: 1, color: "slate" },
  { stage: "Closed Won", count: 0, color: "emerald" },
  { stage: "Closed Lost", count: 0, color: "red" },
];

export const INITIAL_OPPORTUNITIES: IOpportunityItem[] = [
  {
    id: "opp-1",
    title: "AI Interviewer",
    client: "Pegadaian",
    initials: "PG",
    avatarColor: "blue",
    stage: "POC / Discovery",
    stageBadgeText: "POC",
    updatedAt: "Updated 2h ago",
    value: "IDR 450.000.000",
    probability: 60,
    expectedClose: "30 Nov 2025",
    owner: {
      name: "Rafael Lorenzo",
      avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
      role: "Lead Solutions Architect",
    },
    isFavorite: true,
    about: {
      description:
        "POC untuk solusi AI Interviewer yang membantu proses rekrutmen Pegadaian menjadi lebih efisien dengan analisis kandidat berbasis AI.",
      solution: "AI Interviewer Platform",
      product: "Summon AI Suite",
      picClient: "Andika Pratama",
      department: "Human Capital",
      createdDate: "14 May 2025",
      source: "Referral",
    },
    stageProgress: [
      { stage: "Lead", date: "14 May", status: "completed" },
      { stage: "Qualified", date: "20 May", status: "completed" },
      { stage: "POC / Discovery", date: "28 May", status: "current" },
      { stage: "Proposal", status: "upcoming" },
      { stage: "Negotiation", status: "upcoming" },
      { stage: "Closed", status: "upcoming" },
    ],
    nextSteps: [
      {
        id: "task-1",
        title: "Kirim arsitektur solusi",
        dueDate: "Due today",
        dueBadgeType: "today",
        assignee: {
          name: "Rafael Lorenzo",
          avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
        },
        completed: false,
      },
      {
        id: "task-2",
        title: "Demo teknis ke tim HC",
        dueDate: "Due in 2 days",
        dueBadgeType: "upcoming",
        assignee: {
          name: "Muhammad Arief",
          avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
        },
        completed: false,
      },
      {
        id: "task-3",
        title: "Terima feedback POC",
        dueDate: "Due in 5 days",
        dueBadgeType: "future",
        assignee: {
          name: "Fikri Adriansyah",
          avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
        },
        completed: false,
      },
    ],
    keyContacts: [
      {
        id: "c-1",
        name: "Andika Pratama",
        role: "Human Capital Manager",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
        email: "andika@pegadaian.co.id",
      },
      {
        id: "c-2",
        name: "Dewi Lestari",
        role: "IT Manager",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
        email: "dewi.lestari@pegadaian.co.id",
      },
      {
        id: "c-3",
        name: "Budi Santoso",
        role: "Project Sponsor",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80",
        email: "budi.santoso@pegadaian.co.id",
      },
    ],
    relatedAssets: [
      { id: "a-1", title: "Architecture v1.2", type: "Document", iconType: "doc" },
      { id: "a-2", title: "Demo Recording", type: "Video", iconType: "video" },
      { id: "a-3", title: "POC Plan", type: "Document", iconType: "checklist" },
      { id: "a-4", title: "Technical Proposal", type: "Document", iconType: "proposal" },
    ],
    recentActivity: [
      {
        id: "act-1",
        title: "MoM – Kickoff Meeting",
        author: "Edited by Rafael Lorenzo",
        timeAgo: "2h ago",
        color: "blue",
      },
      {
        id: "act-2",
        title: "Demo teknis telah dijadwalkan",
        author: "by Andika Pratama",
        timeAgo: "1d ago",
        color: "purple",
      },
      {
        id: "act-3",
        title: "Arsitektur solusi v1.2 uploaded",
        author: "by Rafael Lorenzo",
        timeAgo: "2d ago",
        color: "green",
      },
    ],
  },
  {
    id: "opp-2",
    title: "Competitor Intel V+ Short",
    client: "Intel",
    initials: "IN",
    avatarColor: "purple",
    stage: "POC / Discovery",
    stageBadgeText: "POC",
    updatedAt: "Updated 1d ago",
    value: "IDR 320.000.000",
    probability: 50,
    expectedClose: "15 Dec 2025",
    owner: {
      name: "Muhammad Arief",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    },
    about: {
      description: "Automated competitor market intelligence and sentiment monitoring dashboard.",
      solution: "Market Intel Engine",
      product: "Summon Intelligence",
      picClient: "Sarah Jenkins",
      department: "Marketing & Strategy",
      createdDate: "20 May 2025",
      source: "Inbound",
    },
    stageProgress: [
      { stage: "Lead", date: "20 May", status: "completed" },
      { stage: "Qualified", date: "25 May", status: "completed" },
      { stage: "POC / Discovery", date: "01 Jun", status: "current" },
      { stage: "Proposal", status: "upcoming" },
      { stage: "Negotiation", status: "upcoming" },
      { stage: "Closed", status: "upcoming" },
    ],
    nextSteps: [
      {
        id: "t-1",
        title: "Share API benchmark report",
        dueDate: "Due tomorrow",
        dueBadgeType: "upcoming",
        assignee: {
          name: "Muhammad Arief",
          avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
        },
      },
    ],
    keyContacts: [
      {
        id: "c-1",
        name: "Sarah Jenkins",
        role: "Head of Market Intel",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
        email: "sarah.j@intel.com",
      },
    ],
    relatedAssets: [
      { id: "a-1", title: "API Benchmark Specs", type: "Document", iconType: "doc" },
      { id: "a-2", title: "POC Scope Draft", type: "Document", iconType: "checklist" },
    ],
    recentActivity: [
      {
        id: "act-1",
        title: "Initial briefing call concluded",
        author: "by Muhammad Arief",
        timeAgo: "1d ago",
        color: "blue",
      },
    ],
  },
  {
    id: "opp-3",
    title: "Asuransi Umum Videl",
    client: "Videl",
    initials: "VD",
    avatarColor: "green",
    stage: "POC / Discovery",
    stageBadgeText: "POC",
    updatedAt: "Updated 2d ago",
    value: "IDR 280.000.000",
    probability: 45,
    expectedClose: "10 Jan 2026",
    owner: {
      name: "Wibi Susanto",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    },
    about: {
      description: "Automated claims verification and fraud detection using document OCR and LLM reasoning.",
      solution: "Claims Automation",
      product: "Summon Document AI",
      picClient: "Hendrik Wijaya",
      department: "Underwriting",
      createdDate: "01 Jun 2025",
      source: "Referral",
    },
    stageProgress: [
      { stage: "Lead", date: "01 Jun", status: "completed" },
      { stage: "Qualified", date: "08 Jun", status: "completed" },
      { stage: "POC / Discovery", date: "15 Jun", status: "current" },
      { stage: "Proposal", status: "upcoming" },
      { stage: "Negotiation", status: "upcoming" },
      { stage: "Closed", status: "upcoming" },
    ],
    nextSteps: [],
    keyContacts: [],
    relatedAssets: [],
    recentActivity: [],
  },
  {
    id: "opp-4",
    title: "William POC",
    client: "William",
    initials: "WL",
    avatarColor: "orange",
    stage: "POC / Discovery",
    stageBadgeText: "POC",
    updatedAt: "Updated 3d ago",
    value: "IDR 190.000.000",
    probability: 40,
    expectedClose: "20 Jan 2026",
    owner: {
      name: "Rafael Lorenzo",
      avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
    },
    about: {
      description: "E-Commerce order anomaly detection POC.",
      solution: "Anomaly Engine",
      product: "Summon Core",
      picClient: "William Tan",
      department: "Operations",
      createdDate: "05 Jun 2025",
      source: "Website",
    },
    stageProgress: [
      { stage: "Lead", date: "05 Jun", status: "completed" },
      { stage: "Qualified", status: "current" },
      { stage: "POC / Discovery", status: "upcoming" },
      { stage: "Proposal", status: "upcoming" },
      { stage: "Negotiation", status: "upcoming" },
      { stage: "Closed", status: "upcoming" },
    ],
    nextSteps: [],
    keyContacts: [],
    relatedAssets: [],
    recentActivity: [],
  },
  {
    id: "opp-5",
    title: "Sucofindo POC",
    client: "Sucofindo",
    initials: "SC",
    avatarColor: "cyan",
    stage: "POC / Discovery",
    stageBadgeText: "POC",
    updatedAt: "Updated 4d ago",
    value: "IDR 550.000.000",
    probability: 70,
    expectedClose: "15 Nov 2025",
    owner: {
      name: "Fikri Adriansyah",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    },
    about: {
      description: "Enterprise inspection workflow automation and digital certification audit trail.",
      solution: "Inspection Suite",
      product: "Summon Operations",
      picClient: "Bambang Hidayat",
      department: "Auditing",
      createdDate: "10 May 2025",
      source: "Tender",
    },
    stageProgress: [
      { stage: "Lead", date: "10 May", status: "completed" },
      { stage: "Qualified", date: "18 May", status: "completed" },
      { stage: "POC / Discovery", date: "25 May", status: "current" },
      { stage: "Proposal", status: "upcoming" },
      { stage: "Negotiation", status: "upcoming" },
      { stage: "Closed", status: "upcoming" },
    ],
    nextSteps: [],
    keyContacts: [],
    relatedAssets: [],
    recentActivity: [],
  },
  {
    id: "opp-6",
    title: "CIMB POC",
    client: "CIMB",
    initials: "CM",
    avatarColor: "pink",
    stage: "POC / Discovery",
    stageBadgeText: "POC",
    updatedAt: "Updated 5d ago",
    value: "IDR 600.000.000",
    probability: 65,
    expectedClose: "05 Dec 2025",
    owner: {
      name: "Rafael Lorenzo",
      avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
    },
    about: {
      description: "Wealth management client reporting automation.",
      solution: "Reporting AI",
      product: "Summon Enterprise",
      picClient: "David Tan",
      department: "Wealth Management",
      createdDate: "12 May 2025",
      source: "Referral",
    },
    stageProgress: [
      { stage: "Lead", date: "12 May", status: "completed" },
      { stage: "Qualified", date: "20 May", status: "completed" },
      { stage: "POC / Discovery", date: "30 May", status: "current" },
      { stage: "Proposal", status: "upcoming" },
      { stage: "Negotiation", status: "upcoming" },
      { stage: "Closed", status: "upcoming" },
    ],
    nextSteps: [],
    keyContacts: [],
    relatedAssets: [],
    recentActivity: [],
  },
  {
    id: "opp-7",
    title: "Recording Mutiara Multifinance",
    client: "Mutiara Multifinance",
    initials: "MF",
    avatarColor: "green",
    stage: "Qualified",
    stageBadgeText: "Recording",
    updatedAt: "Updated 6d ago",
    value: "IDR 150.000.000",
    probability: 35,
    expectedClose: "28 Feb 2026",
    owner: {
      name: "Wibi Susanto",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    },
    about: {
      description: "Audio call recording transcription and compliance verification system.",
      solution: "Audio AI",
      product: "Summon Audio Suite",
      picClient: "Reza Rahardian",
      department: "Call Center Operations",
      createdDate: "22 May 2025",
      source: "Outbound",
    },
    stageProgress: [
      { stage: "Lead", date: "22 May", status: "completed" },
      { stage: "Qualified", date: "29 May", status: "current" },
      { stage: "POC / Discovery", status: "upcoming" },
      { stage: "Proposal", status: "upcoming" },
      { stage: "Negotiation", status: "upcoming" },
      { stage: "Closed", status: "upcoming" },
    ],
    nextSteps: [],
    keyContacts: [],
    relatedAssets: [],
    recentActivity: [],
  },
  {
    id: "opp-8",
    title: "Orang Tua Group",
    client: "Orang Tua Group",
    initials: "OT",
    avatarColor: "orange",
    stage: "Lead",
    stageBadgeText: "Lead",
    updatedAt: "Updated 1w ago",
    value: "IDR 400.000.000",
    probability: 25,
    expectedClose: "15 Mar 2026",
    owner: {
      name: "Muhammad Arief",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    },
    about: {
      description: "FMCG distributor inventory forecasting and route planner integration.",
      solution: "Inventory AI",
      product: "Summon Logistics",
      picClient: "Denny Setiawan",
      department: "Supply Chain",
      createdDate: "15 May 2025",
      source: "Inbound",
    },
    stageProgress: [
      { stage: "Lead", date: "15 May", status: "current" },
      { stage: "Qualified", status: "upcoming" },
      { stage: "POC / Discovery", status: "upcoming" },
      { stage: "Proposal", status: "upcoming" },
      { stage: "Negotiation", status: "upcoming" },
      { stage: "Closed", status: "upcoming" },
    ],
    nextSteps: [],
    keyContacts: [],
    relatedAssets: [],
    recentActivity: [],
  },
  {
    id: "opp-9",
    title: "SMBC",
    client: "SMBC Indonesia",
    initials: "SM",
    avatarColor: "blue",
    stage: "Lead",
    stageBadgeText: "Lead",
    updatedAt: "Updated 1w ago",
    value: "IDR 750.000.000",
    probability: 30,
    expectedClose: "30 Mar 2026",
    owner: {
      name: "Fikri Adriansyah",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    },
    about: {
      description: "Corporate loan application processing pipeline and customer underwriting automation.",
      solution: "Loan AI Automation",
      product: "Summon Enterprise Banking",
      picClient: "Kenji Sato",
      department: "Corporate Banking",
      createdDate: "18 May 2025",
      source: "Executive Network",
    },
    stageProgress: [
      { stage: "Lead", date: "18 May", status: "current" },
      { stage: "Qualified", status: "upcoming" },
      { stage: "POC / Discovery", status: "upcoming" },
      { stage: "Proposal", status: "upcoming" },
      { stage: "Negotiation", status: "upcoming" },
      { stage: "Closed", status: "upcoming" },
    ],
    nextSteps: [],
    keyContacts: [],
    relatedAssets: [],
    recentActivity: [],
  },
];
