import { reply as assistantReply, options as assistantOptions } from "./assistant/http";
import { httpRouter } from "convex/server";
import { auth } from "./auth";
import { read, options } from "./assets/http";
const http = httpRouter();
auth.addHttpRoutes(http);
http.route({ pathPrefix: "/assets/", method: "GET", handler: read });
http.route({ pathPrefix: "/assets/", method: "OPTIONS", handler: options });
http.route({ path: "/assistant/reply", method: "POST", handler: assistantReply });
http.route({ path: "/assistant/reply", method: "OPTIONS", handler: assistantOptions });
export default http;
