/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */

import React, { useState } from "react";
import { FileText, Download, Check, FileSpreadsheet, ArrowRight } from "lucide-react";
import { RECENT_REPORTS } from "./mock-data";

export function RecentReportsRow({ onOpenExportModal }: { onOpenExportModal?: () => void }) {
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const handleDownload = (report: (typeof RECENT_REPORTS)[0]) => {
    setDownloadingId(report.id);

    // Generate sample report file
    const content = `# ${report.title} - ${report.period}
Generated by Summon Management & Reporting
Date: ${new Date().toLocaleDateString("id-ID")}

1. Executive Summary
- Total Revenue YTD: IDR 24.8B (+18.6% vs last year)
- Active Projects: 32 (85% on-track or good health)
- Total Pipeline Potential: IDR 37.6B (42% win rate)
- Overdue Delivery Tasks: 27

2. Portfolio Highlights
- Top Client: Bank Sinar Bahana (IDR 8.9B, 35.9% contribution)
- Second Largest: PT Pegadaian (IDR 5.6B, 22.6% contribution)
- SANFIND: IDR 4.1B (16.5% contribution)

3. Key Risk Items
- BSB Core Banking System (Health Score: 32, Critical)
- SANFIND Enhancement (Health Score: 45, At Risk)

Document Authorized & Verified.
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.title.toLowerCase().replace(/\s+/g, "_")}_${report.period.toLowerCase().replace(/\s+/g, "_")}.${report.format.toLowerCase() === "xlsx" ? "csv" : "txt"}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setTimeout(() => {
      setDownloadingId(null);
    }, 1500);
  };

  return (
    <div className="shadow-sm rounded-2xl border border-subtle bg-surface-1 p-5">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-sm font-semibold text-primary">Recent Reports</h2>
          <p className="text-xs text-secondary">
            Exported executive intelligence, delivery health, and commercial statements.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={onOpenExportModal}
            className="text-xs shadow-sm inline-flex items-center gap-1.5 rounded-lg bg-accent-primary px-3 py-1.5 font-semibold text-white transition-all hover:bg-accent-primary/90"
          >
            <Download className="size-3.5" />
            Generate Custom Report
          </button>
          <button
            type="button"
            onClick={onOpenExportModal}
            className="text-xs inline-flex items-center gap-1 font-medium text-accent-primary hover:underline"
          >
            View all reports <ArrowRight className="size-3" />
          </button>
        </div>
      </div>

      <div className="mt-4 grid grid-cols-1 gap-3.5 sm:grid-cols-2 lg:grid-cols-5">
        {RECENT_REPORTS.map((report) => {
          const isDownloading = downloadingId === report.id;
          const isSpreadsheet = report.format === "XLSX";

          return (
            <div
              key={report.id}
              className="group hover:border-accent-primary/40 hover:shadow-sm flex flex-col justify-between rounded-xl border border-subtle bg-layer-1 p-3.5 transition-all hover:bg-layer-2"
            >
              <div>
                <div className="flex items-start justify-between gap-2">
                  <div
                    className={`flex size-8 items-center justify-center rounded-lg ${
                      isSpreadsheet
                        ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"
                        : "bg-red-500/10 text-red-600 dark:text-red-400"
                    }`}
                  >
                    {isSpreadsheet ? <FileSpreadsheet className="size-4.5" /> : <FileText className="size-4.5" />}
                  </div>
                  <span
                    className={`rounded px-1.5 py-0.5 text-[10px] font-bold ${
                      isSpreadsheet
                        ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"
                        : "bg-red-500/10 text-red-600 dark:text-red-400"
                    }`}
                  >
                    {report.format}
                  </span>
                </div>

                <div className="mt-2.5">
                  <h3 className="text-xs line-clamp-2 font-semibold text-primary">{report.title}</h3>
                  <p className="mt-0.5 text-[11px] font-medium text-secondary">{report.period}</p>
                </div>
              </div>

              <button
                type="button"
                onClick={() => handleDownload(report)}
                className="text-xs hover:border-accent-primary mt-3 flex items-center justify-center gap-1.5 rounded-lg border border-subtle bg-surface-1 py-1.5 font-medium text-secondary transition-all hover:text-accent-primary"
              >
                {isDownloading ? (
                  <>
                    <Check className="text-emerald-500 size-3.5" />
                    <span className="text-emerald-600 dark:text-emerald-400">Downloaded</span>
                  </>
                ) : (
                  <>
                    <Download className="size-3.5" />
                    <span>Download</span>
                  </>
                )}
              </button>
            </div>
          );
        })}
      </div>
    </div>
  );
}
