# Generated by Django 5.2.15 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("summon", "0002_assistant_conversation_message")]

    operations = [
        migrations.AddField(
            model_name="automationjob", name="input_tokens", field=models.PositiveIntegerField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="automationjob", name="model", field=models.CharField(blank=True, max_length=120)
        ),
        migrations.AddField(
            model_name="automationjob", name="output_tokens", field=models.PositiveIntegerField(blank=True, null=True)
        ),
        migrations.AddField(model_name="automationjob", name="preview_markdown", field=models.TextField(blank=True)),
        migrations.AddField(
            model_name="automationjob", name="provider", field=models.CharField(blank=True, max_length=40)
        ),
        migrations.AddField(
            model_name="automationjob", name="published_at", field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="meeting", name="summary_error", field=models.CharField(blank=True, max_length=80)
        ),
        migrations.AddField(
            model_name="meeting", name="summary_input_tokens", field=models.PositiveIntegerField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="meeting", name="summary_model", field=models.CharField(blank=True, max_length=120)
        ),
        migrations.AddField(
            model_name="meeting", name="summary_output_tokens", field=models.PositiveIntegerField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="meeting", name="summary_provider", field=models.CharField(blank=True, max_length=40)
        ),
    ]
