# Generated by Django 5.2.15 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("summon", "0003_ai_job_and_meeting_metadata")]

    operations = [
        migrations.AddField(
            model_name="generatedartifact",
            name="format",
            field=models.CharField(
                choices=[("page", "Page"), ("pdf", "PDF"), ("docx", "DOCX"), ("xlsx", "XLSX"), ("pptx", "PPTX")],
                default="page",
                max_length=8,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="generatedartifact",
            name="summon_unique_artifact_job",
        ),
        migrations.RemoveConstraint(
            model_name="generatedartifact",
            name="summon_artifact_exactly_one_target",
        ),
        migrations.AddConstraint(
            model_name="generatedartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("job", "format"),
                name="summon_unique_artifact_job_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedartifact",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(format="page", page__isnull=False, file_asset__isnull=True)
                    | models.Q(
                        format__in=("pdf", "docx", "xlsx", "pptx"),
                        page__isnull=True,
                        file_asset__isnull=False,
                    )
                ),
                name="summon_artifact_exactly_one_target",
            ),
        ),
    ]
