# Generated by Django 5.2.15 on 2026-08-25 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
        ('summon', '0006_project_profile_not_assessed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='automation_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_messages', to='summon.automationjob'),
        ),
        migrations.CreateModel(
            name='AssistantAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=120)),
                ('size', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=16)),
                ('extracted_text', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('error', models.CharField(blank=True, max_length=80)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='summon.assistantconversation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('file_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summon_assistant_attachment', to='db.fileasset')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='summon.assistantmessage')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summon_assistant_attachments', to='db.workspace')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
