import { Component, useState } from "react";
import type { ReactNode } from "react";
import { useAction, useQuery } from "convex/react";
import { useSearchParams } from "react-router";
import { api } from "@summon/convex/api";
import type { Id } from "@summon/convex/data-model";
import { Button } from "@plane/propel/button";
import { mutationMessage } from "../commercial/forms";
export function JobPreview({
  jobId,
  workspaceId,
  onBack,
}: {
  jobId: string;
  workspaceId: Id<"workspaces">;
  onBack: () => void;
}) {
  const job = useQuery(api.automation.jobs.resolve, { jobId });
  const projects = useQuery(api.projects.index.list, { workspaceId });
  const publish = useAction(api.automation.publish.document);
  const [, setParams] = useSearchParams();
  const [approval, setApproval] = useState(false);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState("");
  if (!job) return <p role="status">Loading preview…</p>;
  if (job.workspaceId !== workspaceId) return <p role="alert">This preview belongs to another workspace.</p>;
  const project = projects?.find((p) => p._id === job.projectId);
  const canPublish = project && project.membershipRole !== "guest" && project.workspaceRole !== "guest";
  return (
    <article className="space-y-5">
      <Button variant="secondary" onClick={onBack}>
        Back to previews
      </Button>
      <header className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0">
          <p className="text-12 text-secondary">{job.template.name}</p>
          <h2 className="text-24 font-semibold break-words">{job.title}</h2>
        </div>
        <span className="rounded-md bg-layer-1 px-3 py-1 text-12">
          {job.publishedDocumentId ? "Published" : job.status}
        </span>
      </header>
      <dl className="flex flex-wrap gap-x-8 gap-y-3 text-14">
        <div>
          <dt className="text-12 text-secondary">Destination project</dt>
          <dd>{project?.name ?? "Loading project…"}</dd>
        </div>
        {job.model && (
          <div>
            <dt className="text-12 text-secondary">Generated by</dt>
            <dd>
              {job.provider} · {job.model}
            </dd>
          </div>
        )}
      </dl>
      {job.status === "running" && (
        <p role="status">Generation is running. This preview updates when the provider finishes.</p>
      )}
      {job.status === "failed" && (
        <div className="rounded-xl border border-subtle-1 p-5">
          <h3 className="text-16 font-medium">Preview could not be generated</h3>
          <p role="alert" className="mt-2 text-14 text-secondary">
            {job.error === "provider_unconfigured"
              ? "An AI provider is not configured. Ask your administrator to configure one, then create a new preview."
              : "Generation failed or access to a source changed. Check your sources before creating a new preview."}
          </p>
        </div>
      )}
      {job.previewMarkdown && (
        <section aria-label="Generated preview" className="space-y-3">
          <h3 className="text-16 font-medium">Preview</h3>
          <pre className="max-h-[65vh] overflow-auto rounded-xl border border-subtle-1 p-5 text-14 break-words whitespace-pre-wrap">
            {job.previewMarkdown}
          </pre>
        </section>
      )}
      {job.citations.length > 0 && (
        <details>
          <summary className="cursor-pointer text-14">Sources ({job.citations.length})</summary>
          <ul className="mt-3 list-inside list-disc space-y-1 text-14 text-secondary">
            {job.citations.map((source) => (
              <li key={`${source.kind}:${source.id}`}>
                {source.label} · {source.kind}
              </li>
            ))}
          </ul>
          {job.contextTruncated && (
            <p className="mt-2 text-12 text-secondary">Source content was shortened to fit the generation limit.</p>
          )}
        </details>
      )}
      {job.publishedDocumentId ? (
        <Button
          onClick={() =>
            setParams((current) => {
              const next = new URLSearchParams(current);
              next.set("module", "documents");
              next.set("document", job.publishedDocumentId!);
              next.delete("automationJob");
              return next;
            })
          }
        >
          Open document
        </Button>
      ) : (
        job.status === "completed" && (
          <section className="space-y-3 rounded-xl border border-subtle-1 p-5">
            <h3 className="text-16 font-medium">Publish to {project?.name ?? "the destination project"}</h3>
            <p className="text-14 text-secondary">
              Project members will be able to read this document, including content generated from private sources.
              Review the preview before sharing.
            </p>
            {canPublish && (
              <>
                <label className="flex items-start gap-2 text-14">
                  <input
                    type="checkbox"
                    className="mt-1"
                    checked={approval}
                    onChange={(e) => setApproval(e.target.checked)}
                    disabled={pending}
                  />
                  I approve sharing this preview with {project.name} members.
                </label>
                <Button
                  disabled={!approval}
                  loading={pending}
                  onClick={async () => {
                    setPending(true);
                    setError("");
                    try {
                      await publish({ jobId: job._id });
                    } catch (failure) {
                      setError(mutationMessage(failure));
                    } finally {
                      setPending(false);
                    }
                  }}
                >
                  Publish document
                </Button>
              </>
            )}
            {!canPublish && <p className="text-14 text-secondary">Project write access is required to publish.</p>}
          </section>
        )
      )}
      {error && (
        <p role="alert" className="text-14 text-danger-primary">
          {error}
        </p>
      )}
    </article>
  );
}
export class JobBoundary extends Component<{ children: ReactNode; onBack: () => void }, { failed: boolean }> {
  state = { failed: false };
  static getDerivedStateFromError() {
    return { failed: true };
  }
  render() {
    return this.state.failed ? (
      <section className="space-y-3">
        <h2 className="text-20 font-semibold">This preview is unavailable</h2>
        <p role="alert" className="text-14 text-secondary">
          Your access to its project or selected sources may have changed.
        </p>
        <Button variant="secondary" onClick={this.props.onBack}>
          Back to previews
        </Button>
      </section>
    ) : (
      this.props.children
    );
  }
}
