/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as assets_access from "../assets/access.js";
import type * as assets_attachment_lifecycle from "../assets/attachment_lifecycle.js";
import type * as assets_cleanup from "../assets/cleanup.js";
import type * as assets_commentImages from "../assets/commentImages.js";
import type * as assets_content from "../assets/content.js";
import type * as assets_draftAttachments from "../assets/draftAttachments.js";
import type * as assets_draft_access from "../assets/draft_access.js";
import type * as assets_http from "../assets/http.js";
import type * as assets_index from "../assets/index.js";
import type * as assets_meetingRecordings from "../assets/meetingRecordings.js";
import type * as assets_taskAttachments from "../assets/taskAttachments.js";
import type * as assets_task_access from "../assets/task_access.js";
import type * as assets_upload from "../assets/upload.js";
import type * as assistant_access from "../assistant/access.js";
import type * as assistant_actions from "../assistant/actions.js";
import type * as assistant_attachment_upload from "../assistant/attachment_upload.js";
import type * as assistant_attachments from "../assistant/attachments.js";
import type * as assistant_context from "../assistant/context.js";
import type * as assistant_http from "../assistant/http.js";
import type * as assistant_index from "../assistant/index.js";
import type * as assistant_messages from "../assistant/messages.js";
import type * as assistant_provider from "../assistant/provider.js";
import type * as auth from "../auth.js";
import type * as automation_access from "../automation/access.js";
import type * as automation_defaults from "../automation/defaults.js";
import type * as automation_generate from "../automation/generate.js";
import type * as automation_jobs from "../automation/jobs.js";
import type * as automation_publication from "../automation/publication.js";
import type * as automation_publish from "../automation/publish.js";
import type * as automation_templates from "../automation/templates.js";
import type * as better_auth from "../better_auth.js";
import type * as commercial_clients from "../commercial/clients.js";
import type * as commercial_contacts from "../commercial/contacts.js";
import type * as commercial_delivery from "../commercial/delivery.js";
import type * as commercial_directory from "../commercial/directory.js";
import type * as commercial_member_directory from "../commercial/member_directory.js";
import type * as commercial_opportunities from "../commercial/opportunities.js";
import type * as commercial_validation from "../commercial/validation.js";
import type * as crons from "../crons.js";
import type * as cycles_access from "../cycles/access.js";
import type * as cycles_burndown from "../cycles/burndown.js";
import type * as cycles_completion_curve from "../cycles/completion_curve.js";
import type * as cycles_dates from "../cycles/dates.js";
import type * as cycles_index from "../cycles/index.js";
import type * as cycles_progress from "../cycles/progress.js";
import type * as cycles_tasks from "../cycles/tasks.js";
import type * as cycles_transfer from "../cycles/transfer.js";
import type * as cycles_transfer_snapshot from "../cycles/transfer_snapshot.js";
import type * as cycles_workspace from "../cycles/workspace.js";
import type * as documents_access from "../documents/access.js";
import type * as documents_copy from "../documents/copy.js";
import type * as documents_copyActions from "../documents/copyActions.js";
import type * as documents_hierarchy from "../documents/hierarchy.js";
import type * as documents_history from "../documents/history.js";
import type * as documents_historyActions from "../documents/historyActions.js";
import type * as documents_index from "../documents/index.js";
import type * as documents_labels from "../documents/labels.js";
import type * as documents_lifecycle from "../documents/lifecycle.js";
import type * as documents_mentions from "../documents/mentions.js";
import type * as documents_reference_tokens from "../documents/reference_tokens.js";
import type * as documents_references from "../documents/references.js";
import type * as estimates_access from "../estimates/access.js";
import type * as estimates_index from "../estimates/index.js";
import type * as estimates_remap from "../estimates/remap.js";
import type * as estimates_selection from "../estimates/selection.js";
import type * as exports_access from "../exports/access.js";
import type * as exports_index from "../exports/index.js";
import type * as exports_records from "../exports/records.js";
import type * as exports_worker from "../exports/worker.js";
import type * as favorites_access from "../favorites/access.js";
import type * as favorites_index from "../favorites/index.js";
import type * as favorites_reorder from "../favorites/reorder.js";
import type * as favorites_targets from "../favorites/targets.js";
import type * as favorites_views from "../favorites/views.js";
import type * as favorites_write from "../favorites/write.js";
import type * as http from "../http.js";
import type * as identity_access from "../identity/access.js";
import type * as identity_accounts_unlink from "../identity/accounts/unlink.js";
import type * as identity_apiAudit from "../identity/apiAudit.js";
import type * as identity_apiTokens from "../identity/apiTokens.js";
import type * as identity_avatar from "../identity/avatar.js";
import type * as identity_avatar_access from "../identity/avatar_access.js";
import type * as identity_avatar_owner from "../identity/avatar_owner.js";
import type * as identity_avatar_upload from "../identity/avatar_upload.js";
import type * as identity_deactivation_access from "../identity/deactivation/access.js";
import type * as identity_deactivation_index from "../identity/deactivation/index.js";
import type * as identity_emailChange_notifications from "../identity/emailChange/notifications.js";
import type * as identity_entry from "../identity/entry.js";
import type * as identity_external from "../identity/external.js";
import type * as identity_index from "../identity/index.js";
import type * as identity_instance_access from "../identity/instance/access.js";
import type * as identity_instance_authentication from "../identity/instance/authentication.js";
import type * as identity_instance_configuration from "../identity/instance/configuration.js";
import type * as identity_instance_email from "../identity/instance/email.js";
import type * as identity_instance_index from "../identity/instance/index.js";
import type * as identity_instance_oauth from "../identity/instance/oauth.js";
import type * as identity_instance_roster from "../identity/instance/roster.js";
import type * as identity_instance_workspaces from "../identity/instance/workspaces.js";
import type * as identity_mail_availability from "../identity/mail/availability.js";
import type * as identity_mail_config from "../identity/mail/config.js";
import type * as identity_mail_provider from "../identity/mail/provider.js";
import type * as identity_mail_sender from "../identity/mail/sender.js";
import type * as identity_oauth_availability from "../identity/oauth/availability.js";
import type * as identity_oauth_config from "../identity/oauth/config.js";
import type * as identity_oauth_providers from "../identity/oauth/providers.js";
import type * as identity_oauth_sync from "../identity/oauth/sync.js";
import type * as identity_onboarding from "../identity/onboarding.js";
import type * as identity_password_index from "../identity/password/index.js";
import type * as identity_password_policy from "../identity/password/policy.js";
import type * as identity_preferences from "../identity/preferences.js";
import type * as identity_preferences_fields from "../identity/preferences_fields.js";
import type * as identity_profile from "../identity/profile.js";
import type * as identity_profile_owner from "../identity/profile_owner.js";
import type * as identity_session from "../identity/session.js";
import type * as identity_signin_policy from "../identity/signin_policy.js";
import type * as identity_signup_policy from "../identity/signup_policy.js";
import type * as identity_user_owner from "../identity/user_owner.js";
import type * as intakes_access from "../intakes/access.js";
import type * as intakes_configuration_owner from "../intakes/configuration_owner.js";
import type * as intakes_description from "../intakes/description.js";
import type * as intakes_index from "../intakes/index.js";
import type * as intakes_lifecycle from "../intakes/lifecycle.js";
import type * as invitations_access from "../invitations/access.js";
import type * as invitations_delivery from "../invitations/delivery.js";
import type * as invitations_email from "../invitations/email.js";
import type * as invitations_index from "../invitations/index.js";
import type * as lib_documentConversion from "../lib/documentConversion.js";
import type * as mcp_access from "../mcp/access.js";
import type * as mcp_client from "../mcp/client.js";
import type * as mcp_credentials from "../mcp/credentials.js";
import type * as mcp_crypto from "../mcp/crypto.js";
import type * as mcp_invocations from "../mcp/invocations.js";
import type * as mcp_sensitive from "../mcp/sensitive.js";
import type * as mcp_sensitiveAccess from "../mcp/sensitiveAccess.js";
import type * as mcp_stepUp from "../mcp/stepUp.js";
import type * as mcp_tools from "../mcp/tools.js";
import type * as mcp_transport from "../mcp/transport.js";
import type * as mcp_vault from "../mcp/vault.js";
import type * as meetings_access from "../meetings/access.js";
import type * as meetings_index from "../meetings/index.js";
import type * as meetings_summary_access from "../meetings/summary/access.js";
import type * as meetings_summary_document from "../meetings/summary/document.js";
import type * as meetings_summary_generate from "../meetings/summary/generate.js";
import type * as meetings_summary_mom from "../meetings/summary/mom.js";
import type * as meetings_summary_runs from "../meetings/summary/runs.js";
import type * as meetings_summary_title from "../meetings/summary/title.js";
import type * as meetings_summary_transcriptActions from "../meetings/summary/transcriptActions.js";
import type * as meetings_summary_transcripts from "../meetings/summary/transcripts.js";
import type * as meetings_summary_validation from "../meetings/summary/validation.js";
import type * as meetings_tasks from "../meetings/tasks.js";
import type * as meetings_transcription_provider from "../meetings/transcription/provider.js";
import type * as meetings_transcription_runs from "../meetings/transcription/runs.js";
import type * as modules_access from "../modules/access.js";
import type * as modules_index from "../modules/index.js";
import type * as modules_links from "../modules/links.js";
import type * as modules_members from "../modules/members.js";
import type * as modules_progress from "../modules/progress.js";
import type * as modules_tasks from "../modules/tasks.js";
import type * as modules_workspace from "../modules/workspace.js";
import type * as navigation_address from "../navigation/address.js";
import type * as navigation_preferences from "../navigation/preferences.js";
import type * as navigation_recent from "../navigation/recent.js";
import type * as notifications_bulk from "../notifications/bulk.js";
import type * as notifications_cleanup from "../notifications/cleanup.js";
import type * as notifications_delivery from "../notifications/delivery.js";
import type * as notifications_index from "../notifications/index.js";
import type * as notifications_mentions from "../notifications/mentions.js";
import type * as notifications_selection from "../notifications/selection.js";
import type * as notifications_subscriptions from "../notifications/subscriptions.js";
import type * as projects_administration from "../projects/administration.js";
import type * as projects_appearance_schema from "../projects/appearance_schema.js";
import type * as projects_branding from "../projects/branding.js";
import type * as projects_branding_schema from "../projects/branding_schema.js";
import type * as projects_cover from "../projects/cover.js";
import type * as projects_cover_owner from "../projects/cover_owner.js";
import type * as projects_create from "../projects/create.js";
import type * as projects_deletion from "../projects/deletion.js";
import type * as projects_directory from "../projects/directory.js";
import type * as projects_external from "../projects/external.js";
import type * as projects_feature_schema from "../projects/feature_schema.js";
import type * as projects_features from "../projects/features.js";
import type * as projects_form from "../projects/form.js";
import type * as projects_inactivity from "../projects/inactivity.js";
import type * as projects_index from "../projects/index.js";
import type * as projects_lifecycle from "../projects/lifecycle.js";
import type * as projects_metadata_fields from "../projects/metadata_fields.js";
import type * as projects_navigation from "../projects/navigation.js";
import type * as projects_network from "../projects/network.js";
import type * as projects_network_access from "../projects/network_access.js";
import type * as projects_network_schema from "../projects/network_schema.js";
import type * as projects_order from "../projects/order.js";
import type * as projects_order_owner from "../projects/order_owner.js";
import type * as projects_settings from "../projects/settings.js";
import type * as projects_timezone from "../projects/timezone.js";
import type * as publicSharing_access from "../publicSharing/access.js";
import type * as publicSharing_index from "../publicSharing/index.js";
import type * as quickLinks_index from "../quickLinks/index.js";
import type * as quickLinks_validation from "../quickLinks/validation.js";
import type * as reporting_analytics from "../reporting/analytics.js";
import type * as reporting_commercial from "../reporting/commercial.js";
import type * as reporting_documents from "../reporting/documents.js";
import type * as reporting_meetings from "../reporting/meetings.js";
import type * as reporting_overview from "../reporting/overview.js";
import type * as reporting_projects from "../reporting/projects.js";
import type * as reporting_scope from "../reporting/scope.js";
import type * as reporting_tasks from "../reporting/tasks.js";
import type * as resources_index from "../resources/index.js";
import type * as savedViews_access from "../savedViews/access.js";
import type * as savedViews_favorites from "../savedViews/favorites.js";
import type * as savedViews_filters from "../savedViews/filters.js";
import type * as savedViews_index from "../savedViews/index.js";
import type * as savedViews_result_page from "../savedViews/result_page.js";
import type * as savedViews_results from "../savedViews/results.js";
import type * as savedViews_scope from "../savedViews/scope.js";
import type * as savedViews_workspace from "../savedViews/workspace.js";
import type * as savedViews_workspaceChoices from "../savedViews/workspaceChoices.js";
import type * as settings_index from "../settings/index.js";
import type * as settings_logo from "../settings/logo.js";
import type * as settings_logo_owner from "../settings/logo_owner.js";
import type * as settings_metadata from "../settings/metadata.js";
import type * as settings_timezone from "../settings/timezone.js";
import type * as settings_values from "../settings/values.js";
import type * as stickies_content from "../stickies/content.js";
import type * as stickies_index from "../stickies/index.js";
import type * as tasks_access from "../tasks/access.js";
import type * as tasks_activity from "../tasks/activity.js";
import type * as tasks_activity_changes from "../tasks/activity_changes.js";
import type * as tasks_assignees from "../tasks/assignees.js";
import type * as tasks_bulk_memberships from "../tasks/bulk_memberships.js";
import type * as tasks_bulk_properties from "../tasks/bulk_properties.js";
import type * as tasks_center from "../tasks/center.js";
import type * as tasks_commentReactions from "../tasks/commentReactions.js";
import type * as tasks_comments from "../tasks/comments.js";
import type * as tasks_create from "../tasks/create.js";
import type * as tasks_description from "../tasks/description.js";
import type * as tasks_description_content from "../tasks/description_content.js";
import type * as tasks_description_images from "../tasks/description_images.js";
import type * as tasks_discussion_access from "../tasks/discussion_access.js";
import type * as tasks_drafts_access from "../tasks/drafts/access.js";
import type * as tasks_drafts_copy from "../tasks/drafts/copy.js";
import type * as tasks_drafts_fields from "../tasks/drafts/fields.js";
import type * as tasks_drafts_index from "../tasks/drafts/index.js";
import type * as tasks_drafts_validate from "../tasks/drafts/validate.js";
import type * as tasks_hierarchy from "../tasks/hierarchy.js";
import type * as tasks_history from "../tasks/history.js";
import type * as tasks_index from "../tasks/index.js";
import type * as tasks_label_access from "../tasks/label_access.js";
import type * as tasks_label_removal from "../tasks/label_removal.js";
import type * as tasks_labels from "../tasks/labels.js";
import type * as tasks_lifecycle from "../tasks/lifecycle.js";
import type * as tasks_links from "../tasks/links.js";
import type * as tasks_profile from "../tasks/profile.js";
import type * as tasks_progress_totals from "../tasks/progress_totals.js";
import type * as tasks_properties from "../tasks/properties.js";
import type * as tasks_property_updates from "../tasks/property_updates.js";
import type * as tasks_reaction_owner from "../tasks/reaction_owner.js";
import type * as tasks_reactions from "../tasks/reactions.js";
import type * as tasks_relationships from "../tasks/relationships.js";
import type * as tasks_revision from "../tasks/revision.js";
import type * as tasks_rich_content from "../tasks/rich_content.js";
import type * as tasks_states from "../tasks/states.js";
import type * as tasks_status from "../tasks/status.js";
import type * as tasks_votes from "../tasks/votes.js";
import type * as webhooks_actions from "../webhooks/actions.js";
import type * as webhooks_index from "../webhooks/index.js";
import type * as workspaces_index from "../workspaces/index.js";
import type * as workspaces_lifecycle from "../workspaces/lifecycle.js";
import type * as workspaces_member_count from "../workspaces/member_count.js";

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";

declare const fullApi: ApiFromModules<{
  "assets/access": typeof assets_access;
  "assets/attachment_lifecycle": typeof assets_attachment_lifecycle;
  "assets/cleanup": typeof assets_cleanup;
  "assets/commentImages": typeof assets_commentImages;
  "assets/content": typeof assets_content;
  "assets/draftAttachments": typeof assets_draftAttachments;
  "assets/draft_access": typeof assets_draft_access;
  "assets/http": typeof assets_http;
  "assets/index": typeof assets_index;
  "assets/meetingRecordings": typeof assets_meetingRecordings;
  "assets/taskAttachments": typeof assets_taskAttachments;
  "assets/task_access": typeof assets_task_access;
  "assets/upload": typeof assets_upload;
  "assistant/access": typeof assistant_access;
  "assistant/actions": typeof assistant_actions;
  "assistant/attachment_upload": typeof assistant_attachment_upload;
  "assistant/attachments": typeof assistant_attachments;
  "assistant/context": typeof assistant_context;
  "assistant/http": typeof assistant_http;
  "assistant/index": typeof assistant_index;
  "assistant/messages": typeof assistant_messages;
  "assistant/provider": typeof assistant_provider;
  auth: typeof auth;
  "automation/access": typeof automation_access;
  "automation/defaults": typeof automation_defaults;
  "automation/generate": typeof automation_generate;
  "automation/jobs": typeof automation_jobs;
  "automation/publication": typeof automation_publication;
  "automation/publish": typeof automation_publish;
  "automation/templates": typeof automation_templates;
  better_auth: typeof better_auth;
  "commercial/clients": typeof commercial_clients;
  "commercial/contacts": typeof commercial_contacts;
  "commercial/delivery": typeof commercial_delivery;
  "commercial/directory": typeof commercial_directory;
  "commercial/member_directory": typeof commercial_member_directory;
  "commercial/opportunities": typeof commercial_opportunities;
  "commercial/validation": typeof commercial_validation;
  crons: typeof crons;
  "cycles/access": typeof cycles_access;
  "cycles/burndown": typeof cycles_burndown;
  "cycles/completion_curve": typeof cycles_completion_curve;
  "cycles/dates": typeof cycles_dates;
  "cycles/index": typeof cycles_index;
  "cycles/progress": typeof cycles_progress;
  "cycles/tasks": typeof cycles_tasks;
  "cycles/transfer": typeof cycles_transfer;
  "cycles/transfer_snapshot": typeof cycles_transfer_snapshot;
  "cycles/workspace": typeof cycles_workspace;
  "documents/access": typeof documents_access;
  "documents/copy": typeof documents_copy;
  "documents/copyActions": typeof documents_copyActions;
  "documents/hierarchy": typeof documents_hierarchy;
  "documents/history": typeof documents_history;
  "documents/historyActions": typeof documents_historyActions;
  "documents/index": typeof documents_index;
  "documents/labels": typeof documents_labels;
  "documents/lifecycle": typeof documents_lifecycle;
  "documents/mentions": typeof documents_mentions;
  "documents/reference_tokens": typeof documents_reference_tokens;
  "documents/references": typeof documents_references;
  "estimates/access": typeof estimates_access;
  "estimates/index": typeof estimates_index;
  "estimates/remap": typeof estimates_remap;
  "estimates/selection": typeof estimates_selection;
  "exports/access": typeof exports_access;
  "exports/index": typeof exports_index;
  "exports/records": typeof exports_records;
  "exports/worker": typeof exports_worker;
  "favorites/access": typeof favorites_access;
  "favorites/index": typeof favorites_index;
  "favorites/reorder": typeof favorites_reorder;
  "favorites/targets": typeof favorites_targets;
  "favorites/views": typeof favorites_views;
  "favorites/write": typeof favorites_write;
  http: typeof http;
  "identity/access": typeof identity_access;
  "identity/accounts/unlink": typeof identity_accounts_unlink;
  "identity/apiAudit": typeof identity_apiAudit;
  "identity/apiTokens": typeof identity_apiTokens;
  "identity/avatar": typeof identity_avatar;
  "identity/avatar_access": typeof identity_avatar_access;
  "identity/avatar_owner": typeof identity_avatar_owner;
  "identity/avatar_upload": typeof identity_avatar_upload;
  "identity/deactivation/access": typeof identity_deactivation_access;
  "identity/deactivation/index": typeof identity_deactivation_index;
  "identity/emailChange/notifications": typeof identity_emailChange_notifications;
  "identity/entry": typeof identity_entry;
  "identity/external": typeof identity_external;
  "identity/index": typeof identity_index;
  "identity/instance/access": typeof identity_instance_access;
  "identity/instance/authentication": typeof identity_instance_authentication;
  "identity/instance/configuration": typeof identity_instance_configuration;
  "identity/instance/email": typeof identity_instance_email;
  "identity/instance/index": typeof identity_instance_index;
  "identity/instance/oauth": typeof identity_instance_oauth;
  "identity/instance/roster": typeof identity_instance_roster;
  "identity/instance/workspaces": typeof identity_instance_workspaces;
  "identity/mail/availability": typeof identity_mail_availability;
  "identity/mail/config": typeof identity_mail_config;
  "identity/mail/provider": typeof identity_mail_provider;
  "identity/mail/sender": typeof identity_mail_sender;
  "identity/oauth/availability": typeof identity_oauth_availability;
  "identity/oauth/config": typeof identity_oauth_config;
  "identity/oauth/providers": typeof identity_oauth_providers;
  "identity/oauth/sync": typeof identity_oauth_sync;
  "identity/onboarding": typeof identity_onboarding;
  "identity/password/index": typeof identity_password_index;
  "identity/password/policy": typeof identity_password_policy;
  "identity/preferences": typeof identity_preferences;
  "identity/preferences_fields": typeof identity_preferences_fields;
  "identity/profile": typeof identity_profile;
  "identity/profile_owner": typeof identity_profile_owner;
  "identity/session": typeof identity_session;
  "identity/signin_policy": typeof identity_signin_policy;
  "identity/signup_policy": typeof identity_signup_policy;
  "identity/user_owner": typeof identity_user_owner;
  "intakes/access": typeof intakes_access;
  "intakes/configuration_owner": typeof intakes_configuration_owner;
  "intakes/description": typeof intakes_description;
  "intakes/index": typeof intakes_index;
  "intakes/lifecycle": typeof intakes_lifecycle;
  "invitations/access": typeof invitations_access;
  "invitations/delivery": typeof invitations_delivery;
  "invitations/email": typeof invitations_email;
  "invitations/index": typeof invitations_index;
  "lib/documentConversion": typeof lib_documentConversion;
  "mcp/access": typeof mcp_access;
  "mcp/client": typeof mcp_client;
  "mcp/credentials": typeof mcp_credentials;
  "mcp/crypto": typeof mcp_crypto;
  "mcp/invocations": typeof mcp_invocations;
  "mcp/sensitive": typeof mcp_sensitive;
  "mcp/sensitiveAccess": typeof mcp_sensitiveAccess;
  "mcp/stepUp": typeof mcp_stepUp;
  "mcp/tools": typeof mcp_tools;
  "mcp/transport": typeof mcp_transport;
  "mcp/vault": typeof mcp_vault;
  "meetings/access": typeof meetings_access;
  "meetings/index": typeof meetings_index;
  "meetings/summary/access": typeof meetings_summary_access;
  "meetings/summary/document": typeof meetings_summary_document;
  "meetings/summary/generate": typeof meetings_summary_generate;
  "meetings/summary/mom": typeof meetings_summary_mom;
  "meetings/summary/runs": typeof meetings_summary_runs;
  "meetings/summary/title": typeof meetings_summary_title;
  "meetings/summary/transcriptActions": typeof meetings_summary_transcriptActions;
  "meetings/summary/transcripts": typeof meetings_summary_transcripts;
  "meetings/summary/validation": typeof meetings_summary_validation;
  "meetings/tasks": typeof meetings_tasks;
  "meetings/transcription/provider": typeof meetings_transcription_provider;
  "meetings/transcription/runs": typeof meetings_transcription_runs;
  "modules/access": typeof modules_access;
  "modules/index": typeof modules_index;
  "modules/links": typeof modules_links;
  "modules/members": typeof modules_members;
  "modules/progress": typeof modules_progress;
  "modules/tasks": typeof modules_tasks;
  "modules/workspace": typeof modules_workspace;
  "navigation/address": typeof navigation_address;
  "navigation/preferences": typeof navigation_preferences;
  "navigation/recent": typeof navigation_recent;
  "notifications/bulk": typeof notifications_bulk;
  "notifications/cleanup": typeof notifications_cleanup;
  "notifications/delivery": typeof notifications_delivery;
  "notifications/index": typeof notifications_index;
  "notifications/mentions": typeof notifications_mentions;
  "notifications/selection": typeof notifications_selection;
  "notifications/subscriptions": typeof notifications_subscriptions;
  "projects/administration": typeof projects_administration;
  "projects/appearance_schema": typeof projects_appearance_schema;
  "projects/branding": typeof projects_branding;
  "projects/branding_schema": typeof projects_branding_schema;
  "projects/cover": typeof projects_cover;
  "projects/cover_owner": typeof projects_cover_owner;
  "projects/create": typeof projects_create;
  "projects/deletion": typeof projects_deletion;
  "projects/directory": typeof projects_directory;
  "projects/external": typeof projects_external;
  "projects/feature_schema": typeof projects_feature_schema;
  "projects/features": typeof projects_features;
  "projects/form": typeof projects_form;
  "projects/inactivity": typeof projects_inactivity;
  "projects/index": typeof projects_index;
  "projects/lifecycle": typeof projects_lifecycle;
  "projects/metadata_fields": typeof projects_metadata_fields;
  "projects/navigation": typeof projects_navigation;
  "projects/network": typeof projects_network;
  "projects/network_access": typeof projects_network_access;
  "projects/network_schema": typeof projects_network_schema;
  "projects/order": typeof projects_order;
  "projects/order_owner": typeof projects_order_owner;
  "projects/settings": typeof projects_settings;
  "projects/timezone": typeof projects_timezone;
  "publicSharing/access": typeof publicSharing_access;
  "publicSharing/index": typeof publicSharing_index;
  "quickLinks/index": typeof quickLinks_index;
  "quickLinks/validation": typeof quickLinks_validation;
  "reporting/analytics": typeof reporting_analytics;
  "reporting/commercial": typeof reporting_commercial;
  "reporting/documents": typeof reporting_documents;
  "reporting/meetings": typeof reporting_meetings;
  "reporting/overview": typeof reporting_overview;
  "reporting/projects": typeof reporting_projects;
  "reporting/scope": typeof reporting_scope;
  "reporting/tasks": typeof reporting_tasks;
  "resources/index": typeof resources_index;
  "savedViews/access": typeof savedViews_access;
  "savedViews/favorites": typeof savedViews_favorites;
  "savedViews/filters": typeof savedViews_filters;
  "savedViews/index": typeof savedViews_index;
  "savedViews/result_page": typeof savedViews_result_page;
  "savedViews/results": typeof savedViews_results;
  "savedViews/scope": typeof savedViews_scope;
  "savedViews/workspace": typeof savedViews_workspace;
  "savedViews/workspaceChoices": typeof savedViews_workspaceChoices;
  "settings/index": typeof settings_index;
  "settings/logo": typeof settings_logo;
  "settings/logo_owner": typeof settings_logo_owner;
  "settings/metadata": typeof settings_metadata;
  "settings/timezone": typeof settings_timezone;
  "settings/values": typeof settings_values;
  "stickies/content": typeof stickies_content;
  "stickies/index": typeof stickies_index;
  "tasks/access": typeof tasks_access;
  "tasks/activity": typeof tasks_activity;
  "tasks/activity_changes": typeof tasks_activity_changes;
  "tasks/assignees": typeof tasks_assignees;
  "tasks/bulk_memberships": typeof tasks_bulk_memberships;
  "tasks/bulk_properties": typeof tasks_bulk_properties;
  "tasks/center": typeof tasks_center;
  "tasks/commentReactions": typeof tasks_commentReactions;
  "tasks/comments": typeof tasks_comments;
  "tasks/create": typeof tasks_create;
  "tasks/description": typeof tasks_description;
  "tasks/description_content": typeof tasks_description_content;
  "tasks/description_images": typeof tasks_description_images;
  "tasks/discussion_access": typeof tasks_discussion_access;
  "tasks/drafts/access": typeof tasks_drafts_access;
  "tasks/drafts/copy": typeof tasks_drafts_copy;
  "tasks/drafts/fields": typeof tasks_drafts_fields;
  "tasks/drafts/index": typeof tasks_drafts_index;
  "tasks/drafts/validate": typeof tasks_drafts_validate;
  "tasks/hierarchy": typeof tasks_hierarchy;
  "tasks/history": typeof tasks_history;
  "tasks/index": typeof tasks_index;
  "tasks/label_access": typeof tasks_label_access;
  "tasks/label_removal": typeof tasks_label_removal;
  "tasks/labels": typeof tasks_labels;
  "tasks/lifecycle": typeof tasks_lifecycle;
  "tasks/links": typeof tasks_links;
  "tasks/profile": typeof tasks_profile;
  "tasks/progress_totals": typeof tasks_progress_totals;
  "tasks/properties": typeof tasks_properties;
  "tasks/property_updates": typeof tasks_property_updates;
  "tasks/reaction_owner": typeof tasks_reaction_owner;
  "tasks/reactions": typeof tasks_reactions;
  "tasks/relationships": typeof tasks_relationships;
  "tasks/revision": typeof tasks_revision;
  "tasks/rich_content": typeof tasks_rich_content;
  "tasks/states": typeof tasks_states;
  "tasks/status": typeof tasks_status;
  "tasks/votes": typeof tasks_votes;
  "webhooks/actions": typeof webhooks_actions;
  "webhooks/index": typeof webhooks_index;
  "workspaces/index": typeof workspaces_index;
  "workspaces/lifecycle": typeof workspaces_lifecycle;
  "workspaces/member_count": typeof workspaces_member_count;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;

export declare const components: {
  betterAuth: import("../betterAuth/_generated/component.js").ComponentApi<"betterAuth">;
};
