/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as assets_access from "../assets/access.js";
import type * as assets_attachment_lifecycle from "../assets/attachment_lifecycle.js";
import type * as assets_cleanup from "../assets/cleanup.js";
import type * as assets_content from "../assets/content.js";
import type * as assets_draftAttachments from "../assets/draftAttachments.js";
import type * as assets_draft_access from "../assets/draft_access.js";
import type * as assets_http from "../assets/http.js";
import type * as assets_index from "../assets/index.js";
import type * as assets_taskAttachments from "../assets/taskAttachments.js";
import type * as assets_task_access from "../assets/task_access.js";
import type * as assets_upload from "../assets/upload.js";
import type * as assistant_access from "../assistant/access.js";
import type * as assistant_actions from "../assistant/actions.js";
import type * as assistant_attachment_upload from "../assistant/attachment_upload.js";
import type * as assistant_attachments from "../assistant/attachments.js";
import type * as assistant_context from "../assistant/context.js";
import type * as assistant_http from "../assistant/http.js";
import type * as assistant_index from "../assistant/index.js";
import type * as assistant_messages from "../assistant/messages.js";
import type * as assistant_provider from "../assistant/provider.js";
import type * as auth from "../auth.js";
import type * as automation_access from "../automation/access.js";
import type * as automation_defaults from "../automation/defaults.js";
import type * as automation_generate from "../automation/generate.js";
import type * as automation_jobs from "../automation/jobs.js";
import type * as automation_publication from "../automation/publication.js";
import type * as automation_publish from "../automation/publish.js";
import type * as automation_templates from "../automation/templates.js";
import type * as commercial_clients from "../commercial/clients.js";
import type * as commercial_contacts from "../commercial/contacts.js";
import type * as commercial_delivery from "../commercial/delivery.js";
import type * as commercial_directory from "../commercial/directory.js";
import type * as commercial_opportunities from "../commercial/opportunities.js";
import type * as commercial_validation from "../commercial/validation.js";
import type * as crons from "../crons.js";
import type * as cycles_access from "../cycles/access.js";
import type * as cycles_dates from "../cycles/dates.js";
import type * as cycles_index from "../cycles/index.js";
import type * as cycles_tasks from "../cycles/tasks.js";
import type * as documents_access from "../documents/access.js";
import type * as documents_index from "../documents/index.js";
import type * as documents_lifecycle from "../documents/lifecycle.js";
import type * as estimates_access from "../estimates/access.js";
import type * as estimates_index from "../estimates/index.js";
import type * as estimates_remap from "../estimates/remap.js";
import type * as estimates_selection from "../estimates/selection.js";
import type * as favorites_access from "../favorites/access.js";
import type * as favorites_index from "../favorites/index.js";
import type * as favorites_reorder from "../favorites/reorder.js";
import type * as favorites_targets from "../favorites/targets.js";
import type * as favorites_views from "../favorites/views.js";
import type * as favorites_write from "../favorites/write.js";
import type * as http from "../http.js";
import type * as identity_access from "../identity/access.js";
import type * as identity_index from "../identity/index.js";
import type * as identity_preferences from "../identity/preferences.js";
import type * as identity_preferences_fields from "../identity/preferences_fields.js";
import type * as identity_profile from "../identity/profile.js";
import type * as identity_profile_owner from "../identity/profile_owner.js";
import type * as identity_session from "../identity/session.js";
import type * as intakes_access from "../intakes/access.js";
import type * as intakes_index from "../intakes/index.js";
import type * as intakes_lifecycle from "../intakes/lifecycle.js";
import type * as lib_documentConversion from "../lib/documentConversion.js";
import type * as mcp_access from "../mcp/access.js";
import type * as mcp_client from "../mcp/client.js";
import type * as mcp_credentials from "../mcp/credentials.js";
import type * as mcp_crypto from "../mcp/crypto.js";
import type * as mcp_invocations from "../mcp/invocations.js";
import type * as mcp_sensitive from "../mcp/sensitive.js";
import type * as mcp_sensitiveAccess from "../mcp/sensitiveAccess.js";
import type * as mcp_stepUp from "../mcp/stepUp.js";
import type * as mcp_tools from "../mcp/tools.js";
import type * as mcp_transport from "../mcp/transport.js";
import type * as mcp_vault from "../mcp/vault.js";
import type * as meetings_access from "../meetings/access.js";
import type * as meetings_index from "../meetings/index.js";
import type * as meetings_summary_access from "../meetings/summary/access.js";
import type * as meetings_summary_document from "../meetings/summary/document.js";
import type * as meetings_summary_generate from "../meetings/summary/generate.js";
import type * as meetings_summary_mom from "../meetings/summary/mom.js";
import type * as meetings_summary_runs from "../meetings/summary/runs.js";
import type * as meetings_summary_title from "../meetings/summary/title.js";
import type * as meetings_summary_transcriptActions from "../meetings/summary/transcriptActions.js";
import type * as meetings_summary_transcripts from "../meetings/summary/transcripts.js";
import type * as meetings_summary_validation from "../meetings/summary/validation.js";
import type * as meetings_tasks from "../meetings/tasks.js";
import type * as modules_access from "../modules/access.js";
import type * as modules_index from "../modules/index.js";
import type * as modules_members from "../modules/members.js";
import type * as modules_tasks from "../modules/tasks.js";
import type * as navigation_address from "../navigation/address.js";
import type * as navigation_preferences from "../navigation/preferences.js";
import type * as navigation_recent from "../navigation/recent.js";
import type * as notifications_bulk from "../notifications/bulk.js";
import type * as notifications_cleanup from "../notifications/cleanup.js";
import type * as notifications_delivery from "../notifications/delivery.js";
import type * as notifications_index from "../notifications/index.js";
import type * as notifications_mentions from "../notifications/mentions.js";
import type * as notifications_selection from "../notifications/selection.js";
import type * as notifications_subscriptions from "../notifications/subscriptions.js";
import type * as projects_create from "../projects/create.js";
import type * as projects_index from "../projects/index.js";
import type * as projects_settings from "../projects/settings.js";
import type * as projects_timezone from "../projects/timezone.js";
import type * as quickLinks_index from "../quickLinks/index.js";
import type * as quickLinks_validation from "../quickLinks/validation.js";
import type * as reporting_commercial from "../reporting/commercial.js";
import type * as reporting_documents from "../reporting/documents.js";
import type * as reporting_meetings from "../reporting/meetings.js";
import type * as reporting_overview from "../reporting/overview.js";
import type * as reporting_projects from "../reporting/projects.js";
import type * as reporting_scope from "../reporting/scope.js";
import type * as reporting_tasks from "../reporting/tasks.js";
import type * as resources_index from "../resources/index.js";
import type * as savedViews_access from "../savedViews/access.js";
import type * as savedViews_favorites from "../savedViews/favorites.js";
import type * as savedViews_filters from "../savedViews/filters.js";
import type * as savedViews_index from "../savedViews/index.js";
import type * as savedViews_result_page from "../savedViews/result_page.js";
import type * as savedViews_results from "../savedViews/results.js";
import type * as savedViews_scope from "../savedViews/scope.js";
import type * as savedViews_workspace from "../savedViews/workspace.js";
import type * as savedViews_workspaceChoices from "../savedViews/workspaceChoices.js";
import type * as sessions_access from "../sessions/access.js";
import type * as sessions_index from "../sessions/index.js";
import type * as settings_index from "../settings/index.js";
import type * as settings_timezone from "../settings/timezone.js";
import type * as stickies_content from "../stickies/content.js";
import type * as stickies_index from "../stickies/index.js";
import type * as tasks_access from "../tasks/access.js";
import type * as tasks_assignees from "../tasks/assignees.js";
import type * as tasks_center from "../tasks/center.js";
import type * as tasks_commentReactions from "../tasks/commentReactions.js";
import type * as tasks_comments from "../tasks/comments.js";
import type * as tasks_create from "../tasks/create.js";
import type * as tasks_description from "../tasks/description.js";
import type * as tasks_description_content from "../tasks/description_content.js";
import type * as tasks_drafts_access from "../tasks/drafts/access.js";
import type * as tasks_drafts_copy from "../tasks/drafts/copy.js";
import type * as tasks_drafts_fields from "../tasks/drafts/fields.js";
import type * as tasks_drafts_index from "../tasks/drafts/index.js";
import type * as tasks_drafts_validate from "../tasks/drafts/validate.js";
import type * as tasks_hierarchy from "../tasks/hierarchy.js";
import type * as tasks_history from "../tasks/history.js";
import type * as tasks_index from "../tasks/index.js";
import type * as tasks_labels from "../tasks/labels.js";
import type * as tasks_lifecycle from "../tasks/lifecycle.js";
import type * as tasks_links from "../tasks/links.js";
import type * as tasks_properties from "../tasks/properties.js";
import type * as tasks_reaction_owner from "../tasks/reaction_owner.js";
import type * as tasks_reactions from "../tasks/reactions.js";
import type * as tasks_relation_migrations from "../tasks/relation_migrations.js";
import type * as tasks_relationships from "../tasks/relationships.js";
import type * as tasks_revision from "../tasks/revision.js";
import type * as tasks_rich_content from "../tasks/rich_content.js";
import type * as tasks_states from "../tasks/states.js";
import type * as tasks_status from "../tasks/status.js";
import type * as workspaces_index from "../workspaces/index.js";

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";

declare const fullApi: ApiFromModules<{
  "assets/access": typeof assets_access;
  "assets/attachment_lifecycle": typeof assets_attachment_lifecycle;
  "assets/cleanup": typeof assets_cleanup;
  "assets/content": typeof assets_content;
  "assets/draftAttachments": typeof assets_draftAttachments;
  "assets/draft_access": typeof assets_draft_access;
  "assets/http": typeof assets_http;
  "assets/index": typeof assets_index;
  "assets/taskAttachments": typeof assets_taskAttachments;
  "assets/task_access": typeof assets_task_access;
  "assets/upload": typeof assets_upload;
  "assistant/access": typeof assistant_access;
  "assistant/actions": typeof assistant_actions;
  "assistant/attachment_upload": typeof assistant_attachment_upload;
  "assistant/attachments": typeof assistant_attachments;
  "assistant/context": typeof assistant_context;
  "assistant/http": typeof assistant_http;
  "assistant/index": typeof assistant_index;
  "assistant/messages": typeof assistant_messages;
  "assistant/provider": typeof assistant_provider;
  auth: typeof auth;
  "automation/access": typeof automation_access;
  "automation/defaults": typeof automation_defaults;
  "automation/generate": typeof automation_generate;
  "automation/jobs": typeof automation_jobs;
  "automation/publication": typeof automation_publication;
  "automation/publish": typeof automation_publish;
  "automation/templates": typeof automation_templates;
  "commercial/clients": typeof commercial_clients;
  "commercial/contacts": typeof commercial_contacts;
  "commercial/delivery": typeof commercial_delivery;
  "commercial/directory": typeof commercial_directory;
  "commercial/opportunities": typeof commercial_opportunities;
  "commercial/validation": typeof commercial_validation;
  crons: typeof crons;
  "cycles/access": typeof cycles_access;
  "cycles/dates": typeof cycles_dates;
  "cycles/index": typeof cycles_index;
  "cycles/tasks": typeof cycles_tasks;
  "documents/access": typeof documents_access;
  "documents/index": typeof documents_index;
  "documents/lifecycle": typeof documents_lifecycle;
  "estimates/access": typeof estimates_access;
  "estimates/index": typeof estimates_index;
  "estimates/remap": typeof estimates_remap;
  "estimates/selection": typeof estimates_selection;
  "favorites/access": typeof favorites_access;
  "favorites/index": typeof favorites_index;
  "favorites/reorder": typeof favorites_reorder;
  "favorites/targets": typeof favorites_targets;
  "favorites/views": typeof favorites_views;
  "favorites/write": typeof favorites_write;
  http: typeof http;
  "identity/access": typeof identity_access;
  "identity/index": typeof identity_index;
  "identity/preferences": typeof identity_preferences;
  "identity/preferences_fields": typeof identity_preferences_fields;
  "identity/profile": typeof identity_profile;
  "identity/profile_owner": typeof identity_profile_owner;
  "identity/session": typeof identity_session;
  "intakes/access": typeof intakes_access;
  "intakes/index": typeof intakes_index;
  "intakes/lifecycle": typeof intakes_lifecycle;
  "lib/documentConversion": typeof lib_documentConversion;
  "mcp/access": typeof mcp_access;
  "mcp/client": typeof mcp_client;
  "mcp/credentials": typeof mcp_credentials;
  "mcp/crypto": typeof mcp_crypto;
  "mcp/invocations": typeof mcp_invocations;
  "mcp/sensitive": typeof mcp_sensitive;
  "mcp/sensitiveAccess": typeof mcp_sensitiveAccess;
  "mcp/stepUp": typeof mcp_stepUp;
  "mcp/tools": typeof mcp_tools;
  "mcp/transport": typeof mcp_transport;
  "mcp/vault": typeof mcp_vault;
  "meetings/access": typeof meetings_access;
  "meetings/index": typeof meetings_index;
  "meetings/summary/access": typeof meetings_summary_access;
  "meetings/summary/document": typeof meetings_summary_document;
  "meetings/summary/generate": typeof meetings_summary_generate;
  "meetings/summary/mom": typeof meetings_summary_mom;
  "meetings/summary/runs": typeof meetings_summary_runs;
  "meetings/summary/title": typeof meetings_summary_title;
  "meetings/summary/transcriptActions": typeof meetings_summary_transcriptActions;
  "meetings/summary/transcripts": typeof meetings_summary_transcripts;
  "meetings/summary/validation": typeof meetings_summary_validation;
  "meetings/tasks": typeof meetings_tasks;
  "modules/access": typeof modules_access;
  "modules/index": typeof modules_index;
  "modules/members": typeof modules_members;
  "modules/tasks": typeof modules_tasks;
  "navigation/address": typeof navigation_address;
  "navigation/preferences": typeof navigation_preferences;
  "navigation/recent": typeof navigation_recent;
  "notifications/bulk": typeof notifications_bulk;
  "notifications/cleanup": typeof notifications_cleanup;
  "notifications/delivery": typeof notifications_delivery;
  "notifications/index": typeof notifications_index;
  "notifications/mentions": typeof notifications_mentions;
  "notifications/selection": typeof notifications_selection;
  "notifications/subscriptions": typeof notifications_subscriptions;
  "projects/create": typeof projects_create;
  "projects/index": typeof projects_index;
  "projects/settings": typeof projects_settings;
  "projects/timezone": typeof projects_timezone;
  "quickLinks/index": typeof quickLinks_index;
  "quickLinks/validation": typeof quickLinks_validation;
  "reporting/commercial": typeof reporting_commercial;
  "reporting/documents": typeof reporting_documents;
  "reporting/meetings": typeof reporting_meetings;
  "reporting/overview": typeof reporting_overview;
  "reporting/projects": typeof reporting_projects;
  "reporting/scope": typeof reporting_scope;
  "reporting/tasks": typeof reporting_tasks;
  "resources/index": typeof resources_index;
  "savedViews/access": typeof savedViews_access;
  "savedViews/favorites": typeof savedViews_favorites;
  "savedViews/filters": typeof savedViews_filters;
  "savedViews/index": typeof savedViews_index;
  "savedViews/result_page": typeof savedViews_result_page;
  "savedViews/results": typeof savedViews_results;
  "savedViews/scope": typeof savedViews_scope;
  "savedViews/workspace": typeof savedViews_workspace;
  "savedViews/workspaceChoices": typeof savedViews_workspaceChoices;
  "sessions/access": typeof sessions_access;
  "sessions/index": typeof sessions_index;
  "settings/index": typeof settings_index;
  "settings/timezone": typeof settings_timezone;
  "stickies/content": typeof stickies_content;
  "stickies/index": typeof stickies_index;
  "tasks/access": typeof tasks_access;
  "tasks/assignees": typeof tasks_assignees;
  "tasks/center": typeof tasks_center;
  "tasks/commentReactions": typeof tasks_commentReactions;
  "tasks/comments": typeof tasks_comments;
  "tasks/create": typeof tasks_create;
  "tasks/description": typeof tasks_description;
  "tasks/description_content": typeof tasks_description_content;
  "tasks/drafts/access": typeof tasks_drafts_access;
  "tasks/drafts/copy": typeof tasks_drafts_copy;
  "tasks/drafts/fields": typeof tasks_drafts_fields;
  "tasks/drafts/index": typeof tasks_drafts_index;
  "tasks/drafts/validate": typeof tasks_drafts_validate;
  "tasks/hierarchy": typeof tasks_hierarchy;
  "tasks/history": typeof tasks_history;
  "tasks/index": typeof tasks_index;
  "tasks/labels": typeof tasks_labels;
  "tasks/lifecycle": typeof tasks_lifecycle;
  "tasks/links": typeof tasks_links;
  "tasks/properties": typeof tasks_properties;
  "tasks/reaction_owner": typeof tasks_reaction_owner;
  "tasks/reactions": typeof tasks_reactions;
  "tasks/relation_migrations": typeof tasks_relation_migrations;
  "tasks/relationships": typeof tasks_relationships;
  "tasks/revision": typeof tasks_revision;
  "tasks/rich_content": typeof tasks_rich_content;
  "tasks/states": typeof tasks_states;
  "tasks/status": typeof tasks_status;
  "workspaces/index": typeof workspaces_index;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;

export declare const components: {};
