/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */

import type { ICredentialItem, ICredentialKpi } from "./types";

export const CREDENTIAL_KPIS: ICredentialKpi = {
  totalCredentials: 32,
  totalProjects: 8,
  activeAccounts: 28,
  activeAccountsPercentage: 87.5,
  sharedWithMe: 12,
  sharedFromProjects: 6,
  expiringSoon: 3,
  expiringDaysLimit: 30,
  riskyCredentials: 2,
};

export const INITIAL_CREDENTIALS: ICredentialItem[] = [
  {
    id: "cred-1",
    name: "BSB Production Server",
    identifier: "deploy@withsummon.com",
    type: "Server",
    project: "BSB Logistic Management System",
    environment: "Production",
    lastUsed: "2 hours ago",
    status: "active",
    username: "deploy@withsummon.com",
    passwordMasked: "••••••••••••••••",
    passwordRaw: "BSB_Prod_Secure#2024!xK",
    hostIp: "10.20.30.15",
    port: "22",
    protocol: "SSH",
    description: "Production server for BSB Logistic Management System",
    tags: ["production", "critical", "bastion"],
    createdBy: {
      name: "Fikri Adriansyah",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
      date: "17 Jan 2024",
    },
    passwordRotationPolicy: "Every 90 days",
    accessSummary: {
      owner: "Fikri Adriansyah",
      usersWithAccess: 5,
      userGroups: 2,
      lastAccessedBy: {
        name: "Rafael Lorenzo",
        timeAgo: "2 hours ago",
      },
    },
  },
  {
    id: "cred-2",
    name: "BSB Staging Server",
    identifier: "deploy-stg@withsummon.com",
    type: "Server",
    project: "BSB Logistic Management System",
    environment: "Staging",
    lastUsed: "1 day ago",
    status: "active",
    username: "deploy-stg@withsummon.com",
    passwordMasked: "••••••••••••••••",
    passwordRaw: "BSB_Staging_99#Env",
    hostIp: "10.20.30.16",
    port: "22",
    protocol: "SSH",
    description: "Staging and integration testing server for BSB logistics.",
    tags: ["staging", "test", "docker"],
    createdBy: {
      name: "Muhammad Arief",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
      date: "20 Jan 2024",
    },
    passwordRotationPolicy: "Every 180 days",
    accessSummary: {
      owner: "Muhammad Arief",
      usersWithAccess: 12,
      userGroups: 3,
      lastAccessedBy: {
        name: "Muhammad Arief",
        timeAgo: "1 day ago",
      },
    },
  },
  {
    id: "cred-3",
    name: "AWS - BSB Production",
    identifier: "AKIA...7K3L",
    type: "Cloud",
    project: "BSB Logistic Management System",
    environment: "Production",
    lastUsed: "2 days ago",
    status: "active",
    username: "AKIA4X90PZKL7K3L",
    passwordMasked: "••••••••••••••••••••",
    passwordRaw: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
    hostIp: "aws.amazon.com",
    port: "443",
    protocol: "HTTPS",
    description: "AWS IAM Programmatic Access Key for Terraform cloud infrastructure.",
    tags: ["aws", "cloud", "iam", "production"],
    createdBy: {
      name: "Fikri Adriansyah",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
      date: "05 Feb 2024",
    },
    passwordRotationPolicy: "Every 90 days",
    accessSummary: {
      owner: "Fikri Adriansyah",
      usersWithAccess: 3,
      userGroups: 1,
      lastAccessedBy: {
        name: "DevOps CI Bot",
        timeAgo: "2 days ago",
      },
    },
  },
  {
    id: "cred-4",
    name: "SANFIND Database",
    identifier: "sanfind_db_user",
    type: "Database",
    project: "SANFIND Enhancement",
    environment: "Production",
    lastUsed: "3 hours ago",
    status: "active",
    username: "sanfind_db_user",
    passwordMasked: "••••••••••••••••",
    passwordRaw: "Sanfind#Postgres2024!Cluster",
    hostIp: "db.sanfind.internal",
    port: "5432",
    protocol: "PostgreSQL",
    description: "Primary TimescaleDB geospatial coordinate cluster database.",
    tags: ["database", "postgres", "timescale"],
    createdBy: {
      name: "Muhammad Arief",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
      date: "12 Feb 2024",
    },
    passwordRotationPolicy: "Every 60 days",
    accessSummary: {
      owner: "Muhammad Arief",
      usersWithAccess: 6,
      userGroups: 2,
      lastAccessedBy: {
        name: "Muhammad Arief",
        timeAgo: "3 hours ago",
      },
    },
  },
  {
    id: "cred-5",
    name: "GitLab - SANFIND",
    identifier: "gitlab-ci-token",
    type: "API Key",
    project: "SANFIND Enhancement",
    environment: "Production",
    lastUsed: "5 hours ago",
    status: "active",
    username: "gitlab-ci-token",
    passwordMasked: "••••••••••••••••••••",
    passwordRaw: "glpat-xxxxxx9048fjs9f92jklms",
    hostIp: "gitlab.com/summon",
    port: "443",
    protocol: "HTTPS",
    description: "CI/CD pipeline webhook runner access token for automated builds.",
    tags: ["gitlab", "cicd", "token"],
    createdBy: {
      name: "Wibi Susanto",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
      date: "01 Mar 2024",
    },
    passwordRotationPolicy: "Every 90 days",
    accessSummary: {
      owner: "Wibi Susanto",
      usersWithAccess: 8,
      userGroups: 2,
      lastAccessedBy: {
        name: "GitLab Runner #4",
        timeAgo: "5 hours ago",
      },
    },
  },
  {
    id: "cred-6",
    name: "Google Workspace - Summon",
    identifier: "summon@withsummon.com",
    type: "SaaS",
    project: "Internal - Summon",
    environment: "Production",
    lastUsed: "1 day ago",
    status: "active",
    username: "summon@withsummon.com",
    passwordMasked: "••••••••••••••••",
    passwordRaw: "Google#WorkspaceAdmin2024",
    hostIp: "admin.google.com",
    port: "443",
    protocol: "OAuth 2.0",
    description: "Super admin service account for organizational domain management.",
    tags: ["google", "saas", "sso"],
    createdBy: {
      name: "Rafael Lorenzo",
      avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
      date: "10 Jan 2024",
    },
    passwordRotationPolicy: "Every 30 days",
    accessSummary: {
      owner: "Rafael Lorenzo",
      usersWithAccess: 2,
      userGroups: 1,
      lastAccessedBy: {
        name: "Rafael Lorenzo",
        timeAgo: "1 day ago",
      },
    },
  },
  {
    id: "cred-7",
    name: "AURA Server Access",
    identifier: "auraserver@withsummon.com",
    type: "Server",
    project: "AURA Project",
    environment: "Staging",
    lastUsed: "3 days ago",
    status: "active",
    username: "auraserver@withsummon.com",
    passwordMasked: "••••••••••••••••",
    passwordRaw: "AuraStaging#LinuxCluster",
    hostIp: "10.40.50.22",
    port: "22",
    protocol: "SSH",
    description: "Staging host for AURA project backend models and worker nodes.",
    tags: ["aura", "server", "staging"],
    createdBy: {
      name: "Rafael Lorenzo",
      avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
      date: "14 Mar 2024",
    },
    passwordRotationPolicy: "Every 90 days",
    accessSummary: {
      owner: "Rafael Lorenzo",
      usersWithAccess: 7,
      userGroups: 2,
      lastAccessedBy: {
        name: "DevOps Engineer",
        timeAgo: "3 days ago",
      },
    },
  },
  {
    id: "cred-8",
    name: "MinIO - Document Storage",
    identifier: "minio_admin",
    type: "Storage",
    project: "BSB Core Banking System",
    environment: "Production",
    lastUsed: "1 week ago",
    status: "expiring_soon",
    username: "minio_admin",
    passwordMasked: "••••••••••••••••",
    passwordRaw: "MinIO_StorageKey_Secret990",
    hostIp: "s3.internal.summon.com",
    port: "9000",
    protocol: "S3 API",
    description: "Object storage bucket credentials for banking transaction receipts.",
    tags: ["storage", "s3", "minio"],
    createdBy: {
      name: "Fikri Adriansyah",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
      date: "05 Apr 2024",
    },
    passwordRotationPolicy: "Every 30 days",
    accessSummary: {
      owner: "Fikri Adriansyah",
      usersWithAccess: 4,
      userGroups: 1,
      lastAccessedBy: {
        name: "System Worker",
        timeAgo: "1 week ago",
      },
    },
  },
];
